const role = document.body.dataset.role;
const key = 'cooltrack-clickable-demo-v3';
const initial = {
  stations:[{id:'s1',name:'Paknampo 1 Hospital',contact:'คุณนภา',phone:'081-234-5678',assets:42},{id:'s2',name:'Office Building B',contact:'คุณเอก',phone:'089-456-1234',assets:18},{id:'s3',name:'Nakhon Sawan Branch',contact:'คุณเมย์',phone:'098-765-4321',assets:15}],
  assets:[{id:'AC-004718',station:'s1',brand:'Daikin',model:'FTKM18SV2S',serial:'DK-18-784912',location:'Ward W32 · Building A, Floor 2',nextMa:'Overdue 3 days',health:'needs_repair'},{id:'AC-002445',station:'s1',brand:'Mitsubishi Electric',model:'MSY-GN18VF',serial:'ME-18-122445',location:'Pharmacy · Building A, Floor 3',nextMa:'Due in 12 days',health:'ma_due'},{id:'AC-003102',station:'s2',brand:'Carrier',model:'42TVAA018',serial:'CR-18-03102',location:'Meeting room · Floor 2',nextMa:'Due in 4 days',health:'ma_due'},{id:'AC-008219',station:'s3',brand:'Daikin',model:'FTKF15TV2S',serial:'DK-15-08219',location:'Front counter · Ground floor',nextMa:'22 Feb 2027',health:'operational'}],
  jobs:[{id:'JOB-202608000021',station:'s1',asset:'AC-004718',customer:'Paknampo 1 Hospital',description:'AC not cooling — Ward W32',status:'pending',assignee:'Unassigned',age:'2h',type:'Repair',date:'28 Aug 2026'},{id:'JOB-202608000020',station:'s2',asset:'AC-003102',customer:'Office Building B',description:'Scheduled 6-month maintenance',status:'in_progress',assignee:'Vichai',age:'1d',type:'MA',date:'27 Aug 2026'},{id:'JOB-202608000019',station:'s3',asset:'AC-008219',customer:'Nakhon Sawan Branch',description:'Inspect water leakage',status:'done',assignee:'Anan',age:'2d',type:'Repair',date:'26 Aug 2026'}],
  quotes:[{id:'QT-202608-008',station:'s1',customer:'Paknampo 1 Hospital',items:[{name:'Clean wall-mounted AC',qty:2,price:650},{name:'Replace capacitor',qty:1,price:850}],status:'pending'}],
  logs:[{asset:'AC-004718',type:'Repair',detail:'Cleaned drainage tray and checked refrigerant pressure',tech:'Somchai',date:'28 Aug 2026'},{asset:'AC-001238',type:'MA',detail:'6-month preventive maintenance completed',tech:'Somchai',date:'28 Aug 2026'},{asset:'AC-003042',type:'Repair',detail:'Replaced fan motor',tech:'Vichai',date:'26 Aug 2026'}],
  team:[{name:'Apichart P.',role:'Administrator',stations:'All stations'},{name:'Somchai S.',role:'Technician',stations:'Paknampo 1 Hospital'},{name:'Vichai T.',role:'Technician',stations:'Office Building B'},{name:'Anan K.',role:'Technician',stations:'Nakhon Sawan Branch'}]
};
let state = JSON.parse(localStorage.getItem(key) || 'null') || structuredClone(initial);
let view = role === 'admin' ? 'dashboard' : 'today';
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const save = () => localStorage.setItem(key,JSON.stringify(state));
const station = id => state.stations.find(x=>x.id===id);
const asset = id => state.assets.find(x=>x.id===id);
const money = n => '฿'+Number(n).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
const status = s => ({pending:['รอมอบหมาย','amber'],in_progress:['กำลังดำเนินการ','blue'],done:['เสร็จสิ้น','green']}[s]||['เปิดอยู่','soft']);
const health = s => ({operational:['ใช้งานปกติ','green'],ma_due:['ใกล้ถึงรอบ MA','amber'],needs_repair:['ต้องตรวจสอบ','red']}[s]||['ไม่ระบุ','soft']);
function toast(msg){const e=$('#toast');e.textContent=tr(msg);e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function nav(){
  const admin = [['OVERVIEW',[['dashboard','▦','Dashboard'],['analytics','◔','Analytics']]],['OPERATIONS',[['jobs','▤','Work orders'],['assets','❄','AC assets'],['quotes','▧','Quotations']]],['CONFIGURATION',[['stations','⌖','Stations'],['team','♙','Team & permissions']]]];
  const staff = [['MY WORKSPACE',[['today','▦','Today'],['my-jobs','▤','My work orders'],['equipment','❄','AC equipment'],['history','◷','Service history']]],['TOOLS',[['scan','▣','Scan QR code'],['request','＋','Request service']]]];
  const groups = role==='admin'?admin:staff;
  const loc = role==='admin'?'<i></i><span><small>WORKSPACE</small><b>CoolTrack Service</b></span><span>⌄</span>':'<span class="pin">⌖</span><span><small>YOUR STATION</small><b>Paknampo 1 Hospital</b></span><span>⌄</span>';
  $('#sidebar').className='sidebar '+role;
  $('#sidebar').innerHTML=`<a class="brand" href="${role==='admin'?'index.html':'station.html'}"><span class="brand-mark">❄</span><span>cooltrack<small>${role==='admin'?'OPERATIONS SYSTEM':'STATION WORKSPACE'}</small></span></a><div class="workspace">${loc}</div><nav class="menu">${groups.map(([label,items])=>`<span class="menu-label">${label}</span>${items.map(([id,icon,title])=>`<button data-nav="${id}" class="${view===id?'active':''}"><i>${icon}</i>${title}${id==='jobs'||id==='my-jobs'?`<span class="counter">${state.jobs.filter(j=>j.status!=='done'&&(role==='admin'||j.station==='s1')).length}</span>`:''}</button>`).join('')}`).join('')}</nav><div class="sidebar-foot"><a class="switch-role" href="${role==='admin'?'station.html':'index.html'}"><span>${role==='admin'?'♟':'♙'}</span><span><small>VIEW AS</small><b>${role==='admin'?'Station staff':'Admin console'} →</b></span></a><div class="hint">Demo mode · stored in this browser</div></div>`;
}
function topbar(){ $('#topbar').innerHTML=role==='admin'?`<div class="search">⌕ <input data-search placeholder="Search order, asset, customer…"><kbd>⌘ K</kbd></div><div class="account"><button class="bell">♢</button><span class="avatar">AP</span><span><b>Apichart P.</b><small>Administrator</small></span></div>`:`<div class="top-title"><small>STATION WORKSPACE</small><b>Paknampo 1 Hospital</b></div><div class="account"><button class="bell">♢</button><span class="avatar staff">SS</span><span><b>Somchai S.</b><small>Technician</small></span></div>` }
function header(title,description,buttons=''){return `<div class="page-head"><div><p class="eyebrow">${role==='admin'?'COOLTRACK DEMO':'PAKNAMPO 1 HOSPITAL'}</p><h1>${title}</h1><p class="sub">${description}</p></div><div class="actions">${buttons}</div></div>`}
function dashboard(){let open=state.jobs.filter(j=>j.status!=='done'),due=state.assets.filter(a=>a.health!=='operational');return `<div class="content"><div class="hero"><div><p class="eyebrow">FRIDAY, 28 AUGUST 2026</p><h1>Good morning, Apichart <span>👋</span></h1><p class="sub">Here is what needs your attention across all stations today.</p></div><div class="actions"><a class="btn secondary" href="station.html">Open station view</a><button class="btn primary" data-action="new-job">＋ New work order</button></div></div><div class="stats"><article class="stat"><span class="icon blue-bg">▤</span><div><small>OPEN WORK ORDERS</small><strong>${open.length}</strong><p><b class="up">↑ 12%</b> from last week</p></div><a data-nav="jobs">View →</a></article><article class="stat"><span class="icon amber-bg">⌛</span><div><small>AWAITING ASSIGNMENT</small><strong>${state.jobs.filter(j=>j.status==='pending').length}</strong><p><b class="warn">2 need action today</b></p></div><a data-nav="jobs">Review →</a></article><article class="stat"><span class="icon red-bg">♢</span><div><small>MA DUE / OVERDUE</small><strong>${due.length}</strong><p><b class="danger">1 overdue</b> · 2 this month</p></div><a data-nav="assets">Resolve →</a></article><article class="stat"><span class="icon green-bg">✓</span><div><small>COMPLETED THIS MONTH</small><strong>${state.jobs.filter(j=>j.status==='done').length+15}</strong><p><b class="up">↑ 4</b> compared to July</p></div><a data-nav="analytics">Report →</a></article></div><div class="grid"><section class="panel performance"><header><div><h2>Service performance</h2><p>Completed work orders by month</p></div><select class="select"><option>Last 6 months</option></select></header><div class="chart"><div class="axis"><span>30</span><span>20</span><span>10</span><span>0</span></div><div class="bars"><span class="bar"><i style="height:36%"></i><small>Mar</small></span><span class="bar"><i style="height:49%"></i><small>Apr</small></span><span class="bar"><i style="height:41%"></i><small>May</small></span><span class="bar"><i style="height:67%"></i><small>Jun</small></span><span class="bar"><i style="height:56%"></i><small>Jul</small></span><span class="bar current"><i style="height:78%"><b>18</b></i><small>Aug</small></span></div></div><footer><span>● Completed jobs</span><b>+12.5% vs. last month</b></footer></section><section class="panel"><header><div><h2>Needs attention</h2><p>Prioritise these items first</p></div></header>${due.slice(0,3).map(a=>`<div class="attention-item"><span class="alert ${a.health==='ma_due'?'amber':''}">${a.health==='needs_repair'?'!':'⌛'}</span><div><b>${esc(a.id)} — ${esc(health(a.health)[0])}</b><p>${esc(station(a.station).name)} · ${esc(a.nextMa)}</p></div><button class="text-btn" data-action="view-asset" data-id="${a.id}">Open</button></div>`).join('')}</section></div>${recentJobs()}</div>`}
function recentJobs(){return `<section class="panel wide"><header><div><h2>Recent work orders</h2><p>Latest activity from every station</p></div><button class="text-btn" data-nav="jobs">View all work orders →</button></header>${jobsTable(state.jobs.slice(0,5))}</section>${stationCards()}`}
function jobsTable(jobs){return `<div class="table-wrap"><table><thead><tr><th>WORK ORDER</th><th>CLIENT / LOCATION</th><th>ASSIGNED TO</th><th>AGE</th><th>STATUS</th><th></th></tr></thead><tbody>${jobs.map(j=>{let s=status(j.status);return `<tr><td><b>${j.id}</b><small>${esc(j.type)} · ${esc(j.asset||'No asset')}</small></td><td><b>${esc(j.customer)}</b><small>${esc(j.description)}</small></td><td>${esc(j.assignee)}</td><td><b>${j.age}</b></td><td><span class="badge ${s[1]}">${s[0]}</span></td><td><button class="text-btn" data-action="view-job" data-id="${j.id}">Open →</button></td></tr>`}).join('')}</tbody></table></div>`}
function stationCards(){return `<section><div class="section-head"><div><h2>Station health</h2><p>Quick view of operations by site</p></div><button class="text-btn" data-nav="stations">Manage stations →</button></div><div class="station-grid">${state.stations.map(s=>{let jobs=state.jobs.filter(j=>j.station===s.id&&j.status!=='done').length, issues=state.assets.filter(a=>a.station===s.id&&a.health!=='operational').length;return `<article class="station-card"><div class="station-title"><span class="icon blue-bg">⌖</span><div><b>${esc(s.name)}</b><small>${s.assets} AC assets</small></div><span class="live">● Live</span></div><div class="station-metrics"><span><b>${jobs}</b> open jobs</span><span><b class="${issues?'danger':''}">${issues}</b> action needed</span></div><button class="text-btn" data-action="station-filter" data-id="${s.id}">View operations →</button></article>`}).join('')}</div></section>`}
function jobsPage(){return `<div class="content">${header('Work orders','Create, assign, track, and complete service work.','<button class="btn primary" data-action="new-job">＋ New work order</button>')}<div class="filter-row"><input data-job-filter placeholder="Search work order, customer, AC ID…"><select data-job-status><option value="all">All statuses</option><option value="pending">Awaiting assignment</option><option value="in_progress">In progress</option><option value="done">Completed</option></select></div><section class="panel">${jobsTable(state.jobs)}</section></div>`}
function assetsPage(){return `<div class="content">${header('AC assets','Equipment master data and maintenance schedules.','<button class="btn secondary" data-action="demo-qr">▣ Scan QR</button><button class="btn primary" data-action="new-asset">＋ Add AC asset</button>')}<div class="filter-row"><input data-asset-filter placeholder="Search Air ID, serial number, model…"><select data-asset-station><option value="all">All stations</option>${state.stations.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="cards-grid" id="asset-grid">${assetCards(state.assets)}</div></div>`}
function assetCards(list){if(!list.length)return '<div class="empty">No equipment matches this search.</div>';return list.map(a=>{let h=health(a.health);return `<article class="panel asset-card"><div class="list-actions"><span class="badge ${h[1]}">${h[0]}</span><span class="badge soft">${esc(station(a.station)?.name||'Unknown')}</span></div><h3>${esc(a.id)}</h3><p>${esc(a.brand)} ${esc(a.model)}</p><div class="detail-grid" style="padding:14px 0 0;grid-template-columns:1fr 1fr"><div class="detail"><small>Serial number</small><b>${esc(a.serial)}</b></div><div class="detail"><small>Next MA</small><b class="${a.health==='needs_repair'?'danger':''}">${esc(a.nextMa)}</b></div></div><footer><span>${esc(a.location)}</span><button class="text-btn" data-action="view-asset" data-id="${a.id}">Details →</button></footer></article>`}).join('')}
function assetDetail(id){let a=asset(id);if(!a)return toast('Asset not found');let h=health(a.health),logs=state.logs.filter(x=>x.asset===id);view='asset-detail';$('#app').innerHTML=`<div class="content">${header(a.id,`${a.brand} ${a.model} · ${station(a.station).name}`,`<button class="btn secondary" data-nav="assets">← Back to assets</button><button class="btn primary" data-action="record-service" data-id="${a.id}">＋ Record service</button>`)}<section class="panel"><header><div><h2>Equipment details <span class="badge ${h[1]}">${h[0]}</span></h2><p>QR target: /ac/${a.id}</p></div><button class="text-btn" data-action="demo-qr">▣ Open QR demo</button></header><div class="detail-grid"><div class="detail"><small>Air ID</small><b>${a.id}</b></div><div class="detail"><small>Serial number</small><b>${esc(a.serial)}</b></div><div class="detail"><small>Station</small><b>${esc(station(a.station).name)}</b></div><div class="detail"><small>Location</small><b>${esc(a.location)}</b></div><div class="detail"><small>Next maintenance</small><b>${esc(a.nextMa)}</b></div><div class="detail"><small>Model</small><b>${esc(a.brand)} ${esc(a.model)}</b></div></div></section><section class="panel wide"><header><div><h2>Service history</h2><p>${logs.length} service records</p></div></header>${logs.length?`<div class="table-wrap"><table><thead><tr><th>DATE</th><th>TYPE</th><th>TECHNICIAN</th><th>DETAIL</th></tr></thead><tbody>${logs.map(l=>`<tr><td>${l.date}</td><td><span class="badge blue">${l.type}</span></td><td>${esc(l.tech)}</td><td>${esc(l.detail)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No service record yet.</div>'}</section></div>`}
function quotesPage(){return `<div class="content">${header('Quotations','Create a quotation with automatic VAT 7% calculation.','<button class="btn primary" data-action="new-quote">＋ New quotation</button>')}<section class="panel">${state.quotes.length?`<div class="table-wrap"><table><thead><tr><th>QUOTATION</th><th>CUSTOMER</th><th>STATION</th><th>TOTAL</th><th>STATUS</th><th></th></tr></thead><tbody>${state.quotes.map(q=>{let sub=q.items.reduce((n,i)=>n+i.qty*i.price,0);return `<tr><td><b>${q.id}</b><small>${q.items.length} item(s)</small></td><td>${esc(q.customer)}</td><td>${esc(station(q.station)?.name||'-')}</td><td><b>${money(sub*1.07)}</b></td><td><span class="badge ${q.status==='approved'?'green':'amber'}">${q.status==='approved'?'Approved':'Pending approval'}</span></td><td><button class="text-btn" data-action="view-quote" data-id="${q.id}">Open →</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No quotations yet. Create your first one.</div>'}</section></div>`}
function quoteDetail(id){let q=state.quotes.find(x=>x.id===id);if(!q)return;let sub=q.items.reduce((n,i)=>n+i.qty*i.price,0),vat=sub*.07;view='quote-detail';$('#app').innerHTML=`<div class="content">${header(q.id,`Quotation for ${q.customer}`,`<button class="btn secondary" data-nav="quotes">← Back</button><button class="btn primary" data-action="approve-quote" data-id="${id}">${q.status==='approved'?'Approved ✓':'Approve quotation'}</button>`)}<section class="panel"><header><div><h2>Quotation items</h2><p>${station(q.station)?.name||''}</p></div></header><div class="table-wrap"><table><thead><tr><th>DESCRIPTION</th><th>QTY</th><th>UNIT PRICE</th><th>TOTAL</th></tr></thead><tbody>${q.items.map(i=>`<tr><td><b>${esc(i.name)}</b></td><td>${i.qty}</td><td>${money(i.price)}</td><td><b>${money(i.qty*i.price)}</b></td></tr>`).join('')}</tbody></table></div><div class="quote-total"><div><span>Subtotal</span><span>${money(sub)}</span></div><div><span>VAT 7%</span><span>${money(vat)}</span></div><div><strong>Total</strong><strong>${money(sub+vat)}</strong></div></div></section></div>`}
function stationsPage(){return `<div class="content">${header('Stations','Manage client sites, contacts, and assigned equipment.','<button class="btn primary" data-action="new-station">＋ Add station</button>')}<div class="cards-grid">${state.stations.map(s=>`<article class="panel asset-card"><span class="icon blue-bg">⌖</span><h3>${esc(s.name)}</h3><p>${s.assets} AC assets · ${state.jobs.filter(j=>j.station===s.id&&j.status!=='done').length} open jobs</p><div class="detail-grid" style="padding:14px 0 0;grid-template-columns:1fr 1fr"><div class="detail"><small>Contact</small><b>${esc(s.contact)}</b></div><div class="detail"><small>Phone</small><b>${esc(s.phone)}</b></div></div><footer><span>Station ID: ${s.id}</span><button class="text-btn" data-action="station-filter" data-id="${s.id}">Open →</button></footer></article>`).join('')}</div></div>`}
function teamPage(){return `<div class="content">${header('Team & permissions','Role-based access is shown here for the prototype.','<button class="btn primary" data-action="new-team">＋ Add team member</button>')}<section class="panel">${jobsTable(state.team.map((p,i)=>({id:'USER-'+String(i+1).padStart(3,'0'),type:p.role,asset:'Access',customer:p.name,description:p.stations,assignee:p.role,age:'Active',status:'done'})))}</section><p class="sub">Demo rule: Admin sees every station. Technician is restricted to their assigned station.</p></div>`}
function staffToday(){let jobs=state.jobs.filter(j=>j.station==='s1'&&j.status!=='done');return `<div class="content"><div class="hero"><div><p class="eyebrow">YOUR SHIFT · FRIDAY, 28 AUG 2026</p><h1>Good morning, Somchai <span>👋</span></h1><p class="sub">You have <b style="color:var(--blue)">${jobs.length} tasks</b> to complete at this station.</p></div><button class="btn primary" data-action="record-service" data-id="AC-004718">＋ Record service</button></div><div class="mini-grid"><article class="panel mini"><span class="icon blue-bg">▤</span><div><small>MY OPEN TASKS</small><b>${jobs.length}</b></div><button class="text-btn" data-nav="my-jobs">See tasks →</button></article><article class="panel mini"><span class="icon amber-bg">◴</span><div><small>DUE TODAY</small><b>${jobs.filter(j=>j.status==='pending').length}</b></div><button class="text-btn" data-nav="my-jobs">Start now →</button></article><article class="panel mini"><span class="icon green-bg">✓</span><div><small>COMPLETED THIS WEEK</small><b>${state.logs.filter(l=>l.tech==='Somchai').length+5}</b></div><button class="text-btn" data-nav="history">View history →</button></article></div><div class="task-grid"><section class="panel"><header><div><h2>Today’s tasks</h2><p>Complete service records after every visit</p></div><span class="badge soft">28 Aug</span></header>${taskCards(jobs)}</section><aside class="rail"><section class="panel scan"><div class="scan-icon">▣</div><h3>Got a new job?</h3><p>Scan the QR code on the AC unit to see its history and record a service.</p><button class="btn secondary" data-action="demo-qr">▣ Scan equipment QR</button><button class="text-btn" data-nav="equipment">or search equipment</button></section><section class="panel"><header><div><h2>Equipment at a glance</h2><p>Paknampo 1 Hospital</p></div></header><div class="detail-grid"><div class="detail"><small>Operational</small><b class="up">${state.assets.filter(a=>a.station==='s1'&&a.health==='operational').length+38}</b></div><div class="detail"><small>Need attention</small><b class="danger">${state.assets.filter(a=>a.station==='s1'&&a.health!=='operational').length}</b></div></div></section></aside></div></div>`}
function taskCards(jobs){return jobs.length?jobs.map(j=>`<article class="task ${j.asset==='AC-004718'?'priority':''}"><span class="task-check"></span><div class="task-info"><small>${j.date} · ${j.type.toUpperCase()}</small><h3>${esc(j.description)}</h3><p>${j.asset||'No AC'} · ${esc(station(j.station).name)}</p><div class="tags"><span class="badge ${status(j.status)[1]}">${status(j.status)[0]}</span>${j.asset&&asset(j.asset)?.health!=='operational'?'<span class="badge red">Attention needed</span>':''}</div></div>${j.status==='pending'?`<button class="btn primary" data-action="start-job" data-id="${j.id}">Start task</button>`:j.status==='in_progress'?`<button class="btn primary" data-action="complete-job" data-id="${j.id}">Complete</button>`:`<button class="btn secondary" data-action="view-job" data-id="${j.id}">View</button>`}</article>`).join(''):'<div class="empty">All tasks completed. Great work!</div>'}
function staffJobs(){return `<div class="content">${header('My work orders','Only work assigned to Paknampo 1 Hospital is visible here.','<button class="btn primary" data-action="new-job">＋ Request service</button>')}<section class="panel">${taskCards(state.jobs.filter(j=>j.station==='s1'))}</section></div>`}
function equipmentPage(){return `<div class="content">${header('AC equipment','Equipment assigned to Paknampo 1 Hospital.','<button class="btn secondary" data-action="demo-qr">▣ Scan QR code</button>')}<div class="cards-grid">${assetCards(state.assets.filter(a=>a.station==='s1'))}</div></div>`}
function historyPage(){let logs=state.logs.filter(l=>l.tech==='Somchai'||['AC-004718','AC-002445'].includes(l.asset));return `<div class="content">${header('Service history','Recent records at your assigned station.','<button class="btn primary" data-action="record-service" data-id="AC-004718">＋ New record</button>')}<section class="panel">${logs.length?`<div class="table-wrap"><table><thead><tr><th>DATE</th><th>AC ASSET</th><th>TYPE</th><th>TECHNICIAN</th><th>DETAIL</th></tr></thead><tbody>${logs.map(l=>`<tr><td>${l.date}</td><td><button class="text-btn" data-action="view-asset" data-id="${l.asset}">${l.asset}</button></td><td><span class="badge blue">${l.type}</span></td><td>${l.tech}</td><td>${esc(l.detail)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No service record yet.</div>'}</section></div>`}
function render(){nav();topbar();const app=$('#app');if(role==='admin'){const views={dashboard,analytics:dashboard,jobs:jobsPage,assets:assetsPage,quotes:quotesPage,stations:stationsPage,team:teamPage};app.innerHTML=(views[view]||dashboard)()}else{const views={today:staffToday,'my-jobs':staffJobs,equipment:equipmentPage,history:historyPage,scan:staffToday,request:staffJobs};app.innerHTML=(views[view]||staffToday)()}}
function modal(title,body){$('#modal').innerHTML=`<form class="modal" data-form="${title}"><header><h2>${tr(title)}</h2><button type="button" class="close" data-action="close-modal">×</button></header>${body}</form>`;$('#modal').classList.add('open');localize($('#modal'))}
function closeModal(){$('#modal').classList.remove('open')}
function optStations(){return state.stations.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}
function optAssets(stationId=''){return state.assets.filter(a=>!stationId||a.station===stationId).map(a=>`<option value="${a.id}">${a.id} — ${a.brand} ${a.model}</option>`).join('')}
function newJob(){modal('New work order',`<div class="form"><div class="two"><label>Station<select name="station">${optStations()}</select></label><label>AC asset (optional)<select name="asset"><option value="">No linked asset</option>${optAssets()}</select></label></div><div class="two"><label>Customer name<input required name="customer" value="Paknampo 1 Hospital"></label><label>Job type<select name="type"><option>Repair</option><option>MA</option><option>Install</option><option>Other</option></select></label></div><label>Job description<textarea required name="description" placeholder="Describe the problem or service requested"></textarea></label></div><div class="form-actions"><button type="button" class="btn secondary" data-action="close-modal">Cancel</button><button class="btn primary">Create work order</button></div>`)}
function newAsset(){modal('Add AC asset',`<div class="form"><div class="two"><label>Air ID<input required name="id" placeholder="AC-005001"></label><label>Station<select name="station">${optStations()}</select></label></div><div class="two"><label>Brand<input required name="brand" placeholder="Daikin"></label><label>Model<input required name="model" placeholder="FTKM18SV2S"></label></div><div class="two"><label>Serial number<input required name="serial"></label><label>Next MA date<input required name="nextMa" type="date"></label></div><label>Installed location<input required name="location" placeholder="Building / Floor / Room"></label></div><div class="form-actions"><button type="button" class="btn secondary" data-action="close-modal">Cancel</button><button class="btn primary">Save asset</button></div>`)}
function newStation(){modal('Add station',`<div class="form"><label>Station name<input required name="name" placeholder="Client / Site name"></label><div class="two"><label>Contact person<input required name="contact"></label><label>Phone<input required name="phone"></label></div></div><div class="form-actions"><button type="button" class="btn secondary" data-action="close-modal">Cancel</button><button class="btn primary">Save station</button></div>`)}
function newQuote(){modal('New quotation',`<div class="form"><div class="two"><label>Station<select name="station">${optStations()}</select></label><label>Customer<input required name="customer" value="Paknampo 1 Hospital"></label></div><label>Items</label><div id="quote-rows"><div class="quote-row"><label>Description<input required name="itemName" value="Clean wall-mounted AC"></label><label>Qty<input required name="itemQty" type="number" min="1" value="1"></label><label>Price<input required name="itemPrice" type="number" min="0" value="650"></label><button type="button" class="text-btn" data-action="remove-quote-row">×</button></div></div><button type="button" class="text-btn" data-action="add-quote-row">＋ Add item</button><div class="quote-total" id="quote-preview"></div></div><div class="form-actions"><button type="button" class="btn secondary" data-action="close-modal">Cancel</button><button class="btn primary">Save quotation</button></div>`);quotePreview()}
function recordService(id){let a=asset(id);modal('Record service',`<div class="form"><label>AC asset<select name="asset">${state.assets.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id} — ${x.brand}</option>`).join('')}</select></label><div class="two"><label>Service type<select name="type"><option>Repair</option><option>MA</option><option>Inspection</option></select></label><label>Next MA date<input name="nextMa" type="date"></label></div><label>Work performed<textarea required name="detail" placeholder="What did you inspect, clean, repair, or replace?"></textarea></label></div><div class="form-actions"><button type="button" class="btn secondary" data-action="close-modal">Cancel</button><button class="btn primary">Save service record</button></div>`)}
function qrModal(){modal('QR scanner demo',`<div class="form"><p class="sub">In the production version this opens the phone camera. For the demo, choose an equipment QR code to simulate a scan.</p><label>Equipment QR<select name="asset">${optAssets(role==='staff'?'s1':'')}</select></label></div><div class="form-actions"><button type="button" class="btn secondary" data-action="close-modal">Cancel</button><button class="btn primary">Open equipment</button></div>`)}
function jobDetail(id){let j=state.jobs.find(x=>x.id===id);if(!j)return;view='job-detail';$('#app').innerHTML=`<div class="content">${header(j.id,`${j.type} · ${j.customer}`,`<button class="btn secondary" data-nav="${role==='admin'?'jobs':'my-jobs'}">← Back</button>${j.status==='pending'?`<button class="btn primary" data-action="start-job" data-id="${id}">Start work</button>`:j.status==='in_progress'?`<button class="btn primary" data-action="complete-job" data-id="${id}">Mark complete</button>`:''}`)}<section class="panel"><header><div><h2>${esc(j.description)}</h2><p>Created ${j.date}</p></div><span class="badge ${status(j.status)[1]}">${status(j.status)[0]}</span></header><div class="detail-grid"><div class="detail"><small>Station</small><b>${esc(station(j.station).name)}</b></div><div class="detail"><small>AC asset</small><b>${j.asset?`<button class="text-btn" data-action="view-asset" data-id="${j.asset}">${j.asset}</button>`:'Not linked'}</b></div><div class="detail"><small>Assigned technician</small><b>${esc(j.assignee)}</b></div><div class="detail"><small>Customer</small><b>${esc(j.customer)}</b></div><div class="detail"><small>Age</small><b>${j.age}</b></div><div class="detail"><small>Work type</small><b>${j.type}</b></div></div></section></div>`}
function quotePreview(){let names=[...document.querySelectorAll('[name=itemName]')],qty=[...document.querySelectorAll('[name=itemQty]')],price=[...document.querySelectorAll('[name=itemPrice]')];if(!names.length)return;let sub=qty.reduce((n,x,i)=>n+(+x.value||0)*(+price[i].value||0),0),v=sub*.07;$('#quote-preview').innerHTML=`<div><span>Subtotal</span><span>${money(sub)}</span></div><div><span>VAT 7%</span><span>${money(v)}</span></div><div><strong>Total</strong><strong>${money(sub+v)}</strong></div>`}
document.addEventListener('click',e=>{let el=e.target.closest('[data-action],[data-nav]');if(!el)return;let a=el.dataset.action,n=el.dataset.nav,id=el.dataset.id;if(n){view=n;render();return}if(a==='close-modal')closeModal();if(a==='new-job')newJob();if(a==='new-asset')newAsset();if(a==='new-station')newStation();if(a==='new-quote')newQuote();if(a==='record-service')recordService(id);if(a==='demo-qr')qrModal();if(a==='view-asset'){assetDetail(id);localize($('#app'))}if(a==='view-job'){jobDetail(id);localize($('#app'))}if(a==='view-quote'){quoteDetail(id);localize($('#app'))}if(a==='station-filter'){view='jobs';render();setTimeout(()=>{$('[data-job-filter]').value=station(id).name;$('[data-job-filter]').dispatchEvent(new Event('input'))},0)}if(a==='start-job'){let j=state.jobs.find(x=>x.id===id);j.status='in_progress';j.assignee='Somchai';save();toast('Work order started');view=role==='admin'?'jobs':'my-jobs';render()}if(a==='complete-job'){let j=state.jobs.find(x=>x.id===id);j.status='done';save();toast('Work order completed');view=role==='admin'?'jobs':'my-jobs';render()}if(a==='approve-quote'){let q=state.quotes.find(x=>x.id===id);q.status='approved';save();toast('Quotation approved');quoteDetail(id);localize($('#app'))}if(a==='add-quote-row'){$('#quote-rows').insertAdjacentHTML('beforeend',`<div class="quote-row"><label>Description<input required name="itemName" value="New item"></label><label>Qty<input required name="itemQty" type="number" min="1" value="1"></label><label>Price<input required name="itemPrice" type="number" min="0" value="0"></label><button type="button" class="text-btn" data-action="remove-quote-row">×</button></div>`);quotePreview();localize($('#quote-rows'))}if(a==='remove-quote-row'){let rows=document.querySelectorAll('.quote-row');if(rows.length>1)el.closest('.quote-row').remove();quotePreview()}});
document.addEventListener('input',e=>{if(e.target.matches('[data-job-filter],[data-asset-filter],[name=itemQty],[name=itemPrice]')){if(e.target.matches('[name=itemQty],[name=itemPrice]'))quotePreview();let q=e.target.value.toLowerCase();if(e.target.matches('[data-job-filter]')){$('.table-wrap tbody').innerHTML=jobsTable(state.jobs.filter(j=>Object.values(j).join(' ').toLowerCase().includes(q))).match(/<tbody>([\s\S]*)<\/tbody>/)[1]}if(e.target.matches('[data-asset-filter]')){$('#asset-grid').innerHTML=assetCards(state.assets.filter(a=>Object.values(a).join(' ').toLowerCase().includes(q)))}}});
document.addEventListener('change',e=>{if(e.target.matches('[data-job-status]')){let v=e.target.value;$('.table-wrap tbody').innerHTML=jobsTable(state.jobs.filter(j=>v==='all'||j.status===v)).match(/<tbody>([\s\S]*)<\/tbody>/)[1]}if(e.target.matches('[data-asset-station]')){$('#asset-grid').innerHTML=assetCards(state.assets.filter(a=>e.target.value==='all'||a.station===e.target.value))}});
document.addEventListener('submit',e=>{if(!e.target.matches('.modal'))return;e.preventDefault();let f=new FormData(e.target),type=e.target.dataset.form;if(type==='New work order'){let id='JOB-202608'+String(22+state.jobs.length).padStart(6,'0');state.jobs.unshift({id,station:f.get('station'),asset:f.get('asset'),customer:f.get('customer'),description:f.get('description'),status:'pending',assignee:'Unassigned',age:'now',type:f.get('type'),date:'28 Aug 2026'});save();closeModal();toast('Work order created');view=role==='admin'?'jobs':'my-jobs';render()}if(type==='Add AC asset'){let id=f.get('id').trim().toUpperCase();if(asset(id))return toast('Air ID already exists');state.assets.unshift({id,station:f.get('station'),brand:f.get('brand'),model:f.get('model'),serial:f.get('serial'),location:f.get('location'),nextMa:f.get('nextMa')||'Not set',health:'operational'});save();closeModal();toast('AC asset added');view='assets';render()}if(type==='Add station'){let id='s'+(state.stations.length+1);state.stations.push({id,name:f.get('name'),contact:f.get('contact')||'-',phone:f.get('phone')||'-',assets:0});save();closeModal();toast('Station added');view='stations';render()}if(type==='New quotation'){let items=[...document.querySelectorAll('.quote-row')].map(r=>({name:r.querySelector('[name=itemName]').value,qty:+r.querySelector('[name=itemQty]').value,price:+r.querySelector('[name=itemPrice]').value}));state.quotes.unshift({id:'QT-202608-'+String(9+state.quotes.length).padStart(3,'0'),station:f.get('station'),customer:f.get('customer'),items,status:'pending'});save();closeModal();toast('Quotation saved');view='quotes';render()}if(type==='Record service'){let a=asset(f.get('asset'));state.logs.unshift({asset:a.id,type:f.get('type'),detail:f.get('detail'),tech:'Somchai',date:'28 Aug 2026'});if(f.get('nextMa')){a.nextMa=f.get('nextMa');a.health='operational'}save();closeModal();toast('Service record saved');assetDetail(a.id);localize($('#app'))}if(type==='QR scanner demo'){closeModal();assetDetail(f.get('asset'));localize($('#app'))}});
const TH = {
  'OVERVIEW':'ภาพรวม','Dashboard':'แดชบอร์ด','Analytics':'วิเคราะห์ข้อมูล','OPERATIONS':'การปฏิบัติงาน','Work orders':'ใบงาน','AC assets':'เครื่องปรับอากาศ','Quotations':'ใบเสนอราคา','CONFIGURATION':'ตั้งค่าระบบ','Stations':'สถานที่ / Station','Team & permissions':'ทีมและสิทธิ์',
  'MY WORKSPACE':'พื้นที่ทำงานของฉัน','Today':'วันนี้','My work orders':'ใบงานของฉัน','AC equipment':'รายการเครื่องปรับอากาศ','Service history':'ประวัติการบริการ','TOOLS':'เครื่องมือ','Scan QR code':'สแกน QR Code','Request service':'แจ้งงานบริการ','VIEW AS':'สลับมุมมอง','Station staff':'เจ้าหน้าที่ Station','Admin console':'ผู้ดูแลระบบ','Demo mode · stored in this browser':'โหมดเดโม · ข้อมูลเก็บในเบราว์เซอร์นี้',
  'WORKSPACE':'พื้นที่ทำงาน','YOUR STATION':'Station ของคุณ','OPERATIONS SYSTEM':'ระบบจัดการงานบริการ','STATION WORKSPACE':'พื้นที่ทำงาน Station','Administrator':'ผู้ดูแลระบบ','Technician':'ช่างเทคนิค','Search order, asset, customer…':'ค้นหาใบงาน, เครื่องแอร์, ลูกค้า…',
  'FRIDAY, 28 AUGUST 2026':'วันศุกร์ที่ 28 สิงหาคม 2569','Good morning, Apichart':'สวัสดี คุณอภิชาติ','Here is what needs your attention across all stations today.':'นี่คือรายการที่ต้องติดตามจากทุก Station ในวันนี้','Open station view':'เปิดมุมมอง Station','New work order':'สร้างใบงาน','OPEN WORK ORDERS':'ใบงานที่ยังเปิดอยู่','from last week':'จากสัปดาห์ก่อน','AWAITING ASSIGNMENT':'รอมอบหมายช่าง','2 need action today':'2 งานต้องดำเนินการวันนี้','MA DUE / OVERDUE':'รอบ MA ใกล้ถึงกำหนด','1 overdue':'1 งานเกินกำหนด','COMPLETED THIS MONTH':'งานเสร็จเดือนนี้','compared to July':'เทียบกับเดือนกรกฎาคม','View →':'ดู →','Review →':'ตรวจสอบ →','Resolve →':'จัดการ →','Report →':'รายงาน →',
  'Service performance':'ประสิทธิภาพงานบริการ','Completed work orders by month':'จำนวนใบงานที่เสร็จในแต่ละเดือน','Last 6 months':'6 เดือนล่าสุด','Completed jobs':'งานเสร็จแล้ว','vs. last month':'เทียบเดือนก่อน','Needs attention':'ต้องติดตาม','Prioritise these items first':'โปรดจัดการรายการเหล่านี้ก่อน','Overdue MA inspection':'ตรวจ MA เกินกำหนด','Unassigned work order':'ใบงานยังไม่มอบหมาย','Quote needs approval':'ใบเสนอราคารออนุมัติ','Open':'เปิด','Assign':'มอบหมาย','Review':'ตรวจสอบ','Recent work orders':'ใบงานล่าสุด','Latest activity from every station':'กิจกรรมล่าสุดจากทุก Station','View all work orders →':'ดูใบงานทั้งหมด →',
  'WORK ORDER':'ใบงาน','CLIENT / LOCATION':'ลูกค้า / สถานที่','ASSIGNED TO':'ผู้รับผิดชอบ','AGE':'ระยะเวลา','STATUS':'สถานะ','Station health':'ภาพรวม Station','Quick view of operations by site':'ดูสถานะการทำงานของแต่ละหน้างาน','Manage stations →':'จัดการ Station →','open jobs':'งานที่เปิดอยู่','action needed':'รายการต้องดำเนินการ','View operations →':'ดูการทำงาน →',
  'Create, assign, track, and complete service work.':'สร้าง มอบหมาย ติดตาม และปิดงานบริการ','All statuses':'ทุกสถานะ','AC assets':'เครื่องปรับอากาศ','Equipment master data and maintenance schedules.':'ข้อมูลเครื่องและกำหนดการบำรุงรักษา','Scan QR':'สแกน QR','Add AC asset':'เพิ่มเครื่องปรับอากาศ','Quotations':'ใบเสนอราคา','Create a quotation with automatic VAT 7% calculation.':'สร้างใบเสนอราคาพร้อมคำนวณ VAT 7% อัตโนมัติ','New quotation':'สร้างใบเสนอราคา','Stations':'สถานที่ / Station','Manage client sites, contacts, and assigned equipment.':'จัดการสถานที่ ลูกค้าผู้ติดต่อ และเครื่องที่รับผิดชอบ','Add station':'เพิ่ม Station','Team & permissions':'ทีมและสิทธิ์','Role-based access is shown here for the prototype.':'เดโมนี้แสดงการแบ่งสิทธิ์ตามบทบาทผู้ใช้','Add team member':'เพิ่มสมาชิกทีม','Demo rule: Admin sees every station. Technician is restricted to their assigned station.':'กติกาเดโม: ผู้ดูแลเห็นทุก Station ส่วนช่างเห็นได้เฉพาะ Station ที่รับผิดชอบ',
  'Operational':'ใช้งานปกติ','MA due':'ใกล้ถึงรอบ MA','Needs repair':'ต้องตรวจสอบ','Details →':'รายละเอียด →','No equipment matches this search.':'ไม่พบเครื่องที่ตรงกับการค้นหา','No quotations yet. Create your first one.':'ยังไม่มีใบเสนอราคา ลองสร้างใบแรกได้เลย','Quotation for':'ใบเสนอราคาสำหรับ','Quotation items':'รายการเสนอราคา','Subtotal':'ยอดก่อน VAT','Total':'ยอดรวมสุทธิ','Back to assets':'กลับไปหน้าเครื่องแอร์','Back':'กลับ','Approve quotation':'อนุมัติใบเสนอราคา','Approved ✓':'อนุมัติแล้ว ✓','Approved':'อนุมัติแล้ว','Pending approval':'รออนุมัติ',
  'YOUR SHIFT · FRIDAY, 28 AUG 2026':'กะงานของคุณ · วันศุกร์ที่ 28 สิงหาคม 2569','Good morning, Somchai':'สวัสดี คุณสมชาย','You have':'คุณมี','tasks':'งาน','to complete at this station.':'ที่ต้องทำใน Station นี้','Record service':'บันทึกงานบริการ','MY OPEN TASKS':'งานที่ยังเปิดอยู่','DUE TODAY':'ครบกำหนดวันนี้','COMPLETED THIS WEEK':'งานเสร็จสัปดาห์นี้','See tasks →':'ดูงาน →','Start now →':'เริ่มงาน →','View history →':'ดูประวัติ →','Today’s tasks':'งานวันนี้','Complete service records after every visit':'บันทึกผลการทำงานหลังจบแต่ละงาน','Got a new job?':'มีงานใหม่?','Scan the QR code on the AC unit to see its history and record a service.':'สแกน QR บนเครื่องแอร์เพื่อดูประวัติและบันทึกงาน','Scan equipment QR':'สแกน QR เครื่อง','or search equipment':'หรือค้นหาเครื่องแอร์','Equipment at a glance':'ภาพรวมเครื่องแอร์',
  'Only work assigned to Paknampo 1 Hospital is visible here.':'หน้านี้แสดงเฉพาะงานของโรงพยาบาลปากน้ำโพ 1','Request service':'แจ้งงานบริการ','Equipment assigned to Paknampo 1 Hospital.':'รายการเครื่องที่อยู่ในโรงพยาบาลปากน้ำโพ 1','Recent records at your assigned station.':'ประวัติรายการบริการของ Station ที่รับผิดชอบ','New record':'บันทึกงานใหม่','No service record yet.':'ยังไม่มีประวัติการบริการ','All tasks completed. Great work!':'ทำงานครบทั้งหมดแล้ว เยี่ยมมาก!',
  'New work order':'สร้างใบงาน','Station':'Station','AC asset (optional)':'เครื่องแอร์ (ไม่บังคับ)','No linked asset':'ไม่ผูกกับเครื่องแอร์','Customer name':'ชื่อลูกค้า','Job type':'ประเภทงาน','Job description':'รายละเอียดงาน','Describe the problem or service requested':'ระบุอาการหรือรายละเอียดบริการที่ต้องการ','Cancel':'ยกเลิก','Create work order':'สร้างใบงาน','Add AC asset':'เพิ่มเครื่องปรับอากาศ','Air ID':'รหัสเครื่อง (Air ID)','Brand':'ยี่ห้อ','Model':'รุ่น','Serial number':'หมายเลข Serial','Next MA date':'วัน MA รอบถัดไป','Installed location':'ตำแหน่งติดตั้ง','Building / Floor / Room':'อาคาร / ชั้น / ห้อง','Save asset':'บันทึกเครื่องแอร์','Add station':'เพิ่ม Station','Station name':'ชื่อ Station','Contact person':'ผู้ติดต่อ','Phone':'โทรศัพท์','Save station':'บันทึก Station','New quotation':'สร้างใบเสนอราคา','Customer':'ลูกค้า','Items':'รายการ','Description':'รายละเอียด','Qty':'จำนวน','Price':'ราคา','Add item':'เพิ่มรายการ','Save quotation':'บันทึกใบเสนอราคา','Record service':'บันทึกงานบริการ','Service type':'ประเภทบริการ','Work performed':'รายละเอียดงานที่ทำ','What did you inspect, clean, repair, or replace?':'ระบุสิ่งที่ตรวจสอบ ล้าง ซ่อม หรือเปลี่ยน','Save service record':'บันทึกประวัติบริการ','QR scanner demo':'เดโมสแกน QR','In the production version this opens the phone camera. For the demo, choose an equipment QR code to simulate a scan.':'ระบบจริงจะเปิดกล้องมือถือ ส่วนเดโมนี้ให้เลือกเครื่องเพื่อจำลองการสแกน','Equipment QR':'QR ของเครื่องแอร์','Open equipment':'เปิดข้อมูลเครื่อง',
  'Work order created':'สร้างใบงานแล้ว','AC asset added':'เพิ่มเครื่องแอร์แล้ว','Station added':'เพิ่ม Station แล้ว','Quotation saved':'บันทึกใบเสนอราคาแล้ว','Service record saved':'บันทึกประวัติบริการแล้ว','Work order started':'เริ่มดำเนินการใบงานแล้ว','Work order completed':'ปิดงานเรียบร้อยแล้ว','Quotation approved':'อนุมัติใบเสนอราคาแล้ว','Air ID already exists':'รหัส Air ID นี้มีอยู่แล้ว','Asset not found':'ไม่พบเครื่องแอร์','Open equipment':'เปิดข้อมูลเครื่อง','Repair':'ซ่อม','Inspection':'ตรวจสอบ','In progress':'กำลังดำเนินการ','Completed':'เสร็จสิ้น','Awaiting assignment':'รอมอบหมาย','Not linked':'ไม่ผูกเครื่องแอร์','Unknown':'ไม่ระบุ','Active':'ใช้งานอยู่','No service record yet.':'ยังไม่มีประวัติการบริการ',
  'Paknampo 1 Hospital':'โรงพยาบาลปากน้ำโพ 1','Office Building B':'อาคารสำนักงาน B','Nakhon Sawan Branch':'สาขานครสวรรค์','AC not cooling — Ward W32':'แอร์ไม่เย็น — ห้อง W32','Scheduled 6-month maintenance':'บำรุงรักษาตามรอบ 6 เดือน','Inspect water leakage':'ตรวจสอบน้ำหยด','Clean wall-mounted AC':'ล้างแอร์แบบติดผนัง','Replace capacitor':'เปลี่ยนคาปาซิเตอร์','Cleaned drainage tray and checked refrigerant pressure':'ล้างถาดน้ำทิ้งและตรวจสอบแรงดันน้ำยา','6-month preventive maintenance completed':'บำรุงรักษาตามรอบ 6 เดือนเสร็จแล้ว','Replaced fan motor':'เปลี่ยนมอเตอร์พัดลม','Ward W32 · Building A, Floor 2':'ห้อง W32 · อาคาร A ชั้น 2','Pharmacy · Building A, Floor 3':'ห้องยา · อาคาร A ชั้น 3','Meeting room · Floor 2':'ห้องประชุม · ชั้น 2','Front counter · Ground floor':'เคาน์เตอร์หน้า · ชั้นล่าง','Overdue 3 days':'เกินกำหนด 3 วัน','Due in 12 days':'ครบกำหนดใน 12 วัน','Due in 4 days':'ครบกำหนดใน 4 วัน','Not set':'ยังไม่กำหนด','Unassigned':'ยังไม่มอบหมาย','now':'เมื่อสักครู่','Mar':'มี.ค.','Apr':'เม.ย.','May':'พ.ค.','Jun':'มิ.ย.','Jul':'ก.ค.','Aug':'ส.ค.'
};
function tr(value){return TH[value]||value}
function localize(root=document.body){
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  let node;while(node=walker.nextNode()){let raw=node.nodeValue,trim=raw.trim();if(!trim)continue;let next=tr(trim);next=next.replace(/^Repair · /,'ซ่อม · ').replace(/^MA · /,'บำรุงรักษา · ').replace(/^Inspection · /,'ตรวจสอบ · ').replace(' from last week',' จากสัปดาห์ก่อน').replace(' compared to July',' เทียบเดือนกรกฎาคม').replace(' · 2 this month',' · 2 งานในเดือนนี้');if(next!==trim)node.nodeValue=raw.replace(trim,next)}
  root.querySelectorAll('[placeholder]').forEach(x=>x.placeholder=tr(x.placeholder));
}
const originalRender=render;render=function(){originalRender();localize(document.body)};
render();
